### ISSUE TITLE
Game does not go past the Online/LAN screen. 

### ISSUE THREAD

**Issue by mckingwastaken** [Wet-Boys/LethalEmotesAPI#104]
**Describe the bug**
Bug appears whenever i have LethalEmotesAPI and BadAssCompany enabled. The problem only goes away when i disable both mods.

**To Reproduce**
1.  Start Game with both mods (or just LethalEmotesAPI) enabled
2.  See Error

**Expected behavior**
It should load in normally. It worked perfectly fine up until a few days ago.

**Logs**
There is no mod called r2modman on the Thunderstore, so i just copied the BepInEx Log from the Command Window.
[log.txt](https://github.com/Wet-Boys/LethalEmotesAPI/files/13990953/log.txt)
![image_2024-01-19_161655748](https://github.com/Wet-Boys/LethalEmotesAPI/assets/76592229/c387b402-099c-42c3-b9a8-82ec5c8dd0af)

**Additional context**
This mod worked fine up until a few days ago, as i have already mentioned above. I tried uninstalling all mods except for this one and BadAssCompany, still didnt work. I tried reinstalling, also didnt work.

**Comment by ToastedOven** [comment]
uhhhh, this is kinda beyond what I am capable of fixing, this is a thunderstore problem not downloading the mod properly. You might have better luck checking in the thunderstore-issues channel on the modding discord https://discord.com/channels/1168655651455639582/1184530215733575910

**Comment by ToastedOven** [comment]
![Discord_p2y6tYMUPK](https://github.com/Wet-Boys/LethalEmotesAPI/assets/49164897/cead4392-34f4-47b1-8a77-46ce5e2427b1)
seems to really just be a thunderstore problem

**Comment by ToastedOven** [comment]
closing this as the issue lies in thunderstore downloading stuff
