### ISSUE TITLE
LethalEmotesAPI spawning enemies when doing random dance

### ISSUE THREAD

**Issue by wildryan** [Wet-Boys/LethalEmotesAPI#111]
**Describe the bug**
With the latest update to LethalEmotesApi, when pressing "F" to random dance, a random enemy spawns on the players location.

Console debugging message as follows
`[Info :Custom Emotes API]Recieved message to play spawn_slime on client. Player (2)`

**To Reproduce**
1. Press F
2. Observe if an enemy spawns, if not try again.

**Expected behavior**
Either nothing happens, or you do an emote with another mod installed

**Screenshots**
![Lethal_Company_xdhQ5i1vvV](https://github.com/Wet-Boys/LethalEmotesAPI/assets/36044992/a0e496ac-5a7a-4727-b54f-3f0332ec3abc)

**ModPack Code**
018d2f77-54e3-0fd2-a9bb-3eb9c0d0c9d4

**Additional context**
`DebugCommands.Debugcommands();
`
This call is happening in `Awake()`, I don't know if it causes this as I haven't really looked into it.

 Even after uninstalling BadAssCompany and Glizzyemotes, I still have this issue

**Comment by Rune580** [comment]
@ToastedOven accidentally left that in from debugging, fixed in 1.3.1
