### ISSUE TITLE
the red console when loading the game

### ISSUE THREAD

**Issue by BAHEK-BOP** [Wet-Boys/LethalEmotesAPI#117]
**Describe the bug**
the red console when loading the game. I forgot to add this happened after updating your mod to the latest version (I'm not sure of course that it's his fault, but still I won't miss this moment)

**Expected behavior**
I expected to see at least some kind of error in the game. BUT nothing

**Screenshots**
![image](https://github.com/Wet-Boys/LethalEmotesAPI/assets/157053836/80e71fed-ce20-4398-aa76-8f028aa2d2e6)

**Logs**

[LogOutput.log](https://github.com/Wet-Boys/LethalEmotesAPI/files/14173511/LogOutput.log)

**ModPack Code**
018d7bfc-557a-e7ba-621c-2095c2461cfa

can you tell me how to use this ModPack code? otherwise, I did not find where to insert it to share with a friend

**Comment by ToastedOven** [comment]
for using the r2modman code, you can follow from this timestamp (for any game supported by r2modman) https://youtu.be/YU6TZuteaVg?si=CFh8QFTRY3Ek_p8t&t=35

As for the issue at hand

https://thunderstore.io/c/lethal-company/p/CCCM/mysticemotes/

and

https://thunderstore.io/c/lethal-company/p/mertvybasein/NekiyManEmotes/

both implement an emote called Popular Vibe, so until one or both of them start using the ImportV2 system, there is nothing I can do to solve that specifically, I'll see about putting out a patch to gracefully step over duplicate emotes using the old import system. But best case scenario would be one of the mods updating to not used the deprecated solution for importing emotes.
