### ISSUE TITLE
How to correctly configure the emoticon that will not be displayed when pressing the random emoticon key

### ISSUE THREAD

**Issue by huluoboya3** [Wet-Boys/LethalEmotesAPI#119]
I tried internal names and custom names and it didn't work
For example: \"com.weliveinasociety.XXX__name\" or \"name\"

**Comment by ToastedOven** [comment]
So you are trying to create emotes that won't show up in the random pool/selectable list correct? In your CustomEmoteParams, set visible equal to false
![devenv_wS8gvQJKsz](https://github.com/Wet-Boys/LethalEmotesAPI/assets/49164897/4d2e15ca-9136-4b11-a41b-41245545fe15)

If that wasn't your ask lemme know

**Comment by huluoboya3** [comment]
Thank you. It worked
