### ISSUE TITLE
When certain fixed animations are played in the air, the player will float

### ISSUE THREAD

**Issue by huluoboya3** [Wet-Boys/LethalEmotesAPI#120]
For example:

https://github.com/Wet-Boys/LethalEmotesAPI/assets/93986295/47e1da2a-8bdf-4f9a-a0d5-6472da817080

**Comment by ToastedOven** [comment]
I should probably fix this... Technically not a bug with EmotesAPI, just kinda how I programmed the emotes themselves, I'll look into it sometime this week

**Comment by ToastedOven** [comment]
fixed with the most recent TF2Emotes update
