### ISSUE TITLE
Can't build project, missing AdvancedCompany dependency

### ISSUE THREAD

**Issue by huluoboya3** [Wet-Boys/LethalEmotesAPI#132]
When I try to build, there is an error from the AdvancedCompany patch.
Even if the build is successful, the expression is out of sync.

**Comment by Rune580** [comment]
Yeah, unfortunately the removal of AC from the thunderstore has broken our build system, we're looking into possible solutions.

**Comment by huluoboya3** [comment]
When I manually reference, it shows that MobileTerminal does not contain the definition of player

**Comment by Rune580** [comment]
Working on a solution right now.

**Comment by Rune580** [comment]
Waiting for checks to pass before merging

**Comment by Rune580** [comment]
pull the most recent commit, should work now
