### ISSUE TITLE
Modeling bug seen when using LethalVRM with certain versions of LethalEmotesAPI

### ISSUE THREAD

**Issue by Nyohot** [Wet-Boys/LethalEmotesAPI#174]
**Describe the bug**
When using LethalVRM and LethalEmotesAPI (1.11.1~1.12.2 ver) together, there is a modeling bug where the arms of existing characters are visible.

**To Reproduce**
using LethalVRM with LethalEmotesAPI(1.11.1~1.12.2 ver)
dance with third person mode

**Screenshots**
![20240510220851_1](https://github.com/Wet-Boys/LethalEmotesAPI/assets/118093722/1eb0336e-fa5c-4921-8488-8aedfb778857)

**Comment by ToastedOven** [comment]
Hey, just testing with a VRM model I have on my end, seems like it's working ok 
![Lethal_Company_1Kblf7F6OU](https://github.com/Wet-Boys/LethalEmotesAPI/assets/49164897/05112bfb-ae8e-42ba-a125-7f8e6ff7cca1)
Do you have a profile code from your pack? It might be some conflict with another mod I can take a look at

**Comment by Nyohot** [comment]
018f632e-d620-85d7-979e-43e823e992cd

This is it

**Comment by Nyohot** [comment]
018f6365-41a6-08c5-6489-6757fd642563
The same thing happened with this code

**Comment by ToastedOven** [comment]
cool, I'm seeing the issue with these packs. I'll get to work on a fix

**Comment by ToastedOven** [comment]
Fixed in 1.12.3, thanks for the report!

**Comment by Nyohot** [comment]
Thank you for solving it
