### ISSUE TITLE
Custom enemy Animator been reset?

### ISSUE THREAD

**Issue by BoredBean** [Wet-Boys/LethalEmotesAPI#177]
**Describe the bug**
My mod replaces the model and the Animator of HoarderBug with my customized AnimController and Animations.
The replacement patches with the EnemyAI's Start() function.
It works well without LethalEmotesAPI.
But it seems the Animator is reset to the original one or the animator replacement failed (without an ERROR log) when LethalEmotesAPI is on, with warnings `[Warning: Unity Log] Could not resolve '***' because it is not a child Transform in the Animator hierarchy.`
My new model doesn't have the same bones as the original model, that's why I have to replace the AnimClips.
And then ERRORs keep popping up like shown below:
```
[Error  : Unity Log] InvalidOperationException: The TransformStreamHandle cannot be resolved.
Stack trace:
UnityEngine.Animations.TransformStreamHandle.CheckIsValidAndResolve (UnityEngine.Animations.AnimationStream& stream) (at <5d72b68986b04a96815303374320f4d3>:0)
UnityEngine.Animations.TransformStreamHandle.SetLocalTRS (UnityEngine.Animations.AnimationStream stream, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Vector3 scale, System.Boolean useMask) (at <5d72b68986b04a96815303374320f4d3>:0)
UnityEngine.Animations.Rigging.RigSyncSceneToStreamJob+TransformSyncer.Sync (UnityEngine.Animations.AnimationStream& stream) (at <810a51f9f25a4da3af6509cb276b430f>:0)
UnityEngine.Animations.Rigging.RigSyncSceneToStreamJob.ProcessAnimation (UnityEngine.Animations.AnimationStream stream) (at <810a51f9f25a4da3af6509cb276b430f>:0)
UnityEngine.Animations.ProcessAnimationJobStruct`1[T].Execute (T& data, System.IntPtr animationStreamPtr, System.IntPtr methodIndex, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) (at <5d72b68986b04a96815303374320f4d3>:0)
```

**To Reproduce**
If you want to reproduce it, just run the game with **LethalEmotesAPI** and **TouhouEnemyModels**.
Once you spawn some HoarderBugs, the ERRORs will show up.

**Expected behaviour**
The ERRORs didn't corrupt all of the AnimClips but caused the FPS drop and the model looks weird.

**Screenshots**

**Logs**
[LogOutput0618.log](https://github.com/user-attachments/files/15876289/LogOutput0618.log)

**ModPack Code**
019027ac-dcf1-450a-c9dc-c0d86ff91f74

**Additional context**
Looking for some information. Thank you.

**Comment by ToastedOven** [comment]
Luckily, seems this was only cause by a single line of code which I kinda just forgot to remove from RoR2 emotesapi, so this problem can be fixed easily
