### ISSUE TITLE
Version 1.13.0: Third Person Model Visible in First Person

### ISSUE THREAD

**Issue by NBeeCC** [Wet-Boys/LethalEmotesAPI#178]
**Describe the bug**
When using the third person camera for emotes and cancelling any emote you will be able to see your third person model while in first person. This is only fixed when using the emote loader for TooManyEmotes (by using either their emote wheel, or using one of their emotes on the main wheel twice).

**To Reproduce**
1.- Open up a Modded instance of Lethal company with both Lethal Emotes API Version 1.13.0: and BadAssCompany.
2.- Do any emote from the wheel.
3.- Stop the emote.
4.- You'll see your own head and your third person body in first person.

**Expected behavior**
Upon finishing your emote you shouldn't be able to see your third person body.

**ModPack Code**
0190d334-6a9f-78d7-1f2b-1d645a18c0b1

**Additional context**
This bug can sometimes be completely fixed when entering a lobby. Though if it is bugged when joining a lobby it will remain bugged until the next fixed join.

**Comment by ToastedOven** [comment]
Ok took a bit but I found the issue. EmotesAPI's third person stuff still applies even when emoting with TME, which shouldn't be the case. This issue can be reproduced 100% of the time. I'll see about fixing this tonight

**Comment by ToastedOven** [comment]
cool, was a quick fix. I pushed it out, 1.13.1 should fix your issue, I'll leave this open for a bit in case I missed something though

**Comment by NBeeCC** [comment]
Just wanted to say that this doesn't only happen when using TME emotes on the regular wheel, but rather when using any emotes from this version on. It may be some other mod conflict, but at the very least the TME emotes don't have this issue when using their own wheel.

**Comment by ToastedOven** [comment]
It's not specific to 1.13.0. I downgraded and I was still seeing the issue on the profile you sent

**Comment by ToastedOven** [comment]
Let me know if you still see the issue on 1.13.1

**Comment by NBeeCC** [comment]
I tried restarting my lobby a few times as that sometimes either broke or fixed it, can confirm at least with a manual install of 1.13.1 (R2Modman doesn't get updates until a bit later) the issue is now **fixed.** Thank you so much! I was going insane trying to troubleshoot mod conflicts on my own. _(If you don't mind I'd also like to DM you about an audio easter egg for BadAssCompany)_
