### ISSUE TITLE
Hi problem compatibility with HDLethalCompany

### ISSUE THREAD

**Issue by Xeraccoon** [Wet-Boys/LethalEmotesAPI#180]
EDIT : I have fix it with using other plugin same work and better work "LCULTRAWIDE" but you can fix it for other, im sure he are happy resolve this bug, i write this message for give info LCULTRAWIDE can replace HDLethalCompany.

**Describe the bug**
Problem compatibility with HDlethalCompany In game When we using the terminal, we are blocked and we can't do anything

**To Reproduce**
just using the terminal

**Screenshots**
https://i.imgur.com/dDRxKNJ.png

**Logs**
[LogOutput.log](https://github.com/user-attachments/files/16674389/LogOutput.log)

**ModPack Code**
01916f5a-15a9-8080-8bee-8f893d3244fe

**Comment by ToastedOven** [comment]
HDLethalCompany hasn't been updated in 8 months and the author has left the mod scene. Last I heard it causes issues in other mods as well. I suggest sticking with what works in your case.
