### ISSUE TITLE
Mouse Cursor not showing

### ISSUE THREAD

**Issue by Sieged3** [Wet-Boys/LethalEmotesAPI#181]
When I click the emote wheel. I try to customize, but there is no mouse cursor. I used a client and what I notice is that the emote mod just puts my mouse cursor at the middle of the screen. Any idea why that is?

**Comment by ToastedOven** [comment]
could be a bug, if you could send a log file that would help narrow that down. It could also be you have a controller plugged in giving very slight inputs which might cause that as well

**Comment by Sieged3** [comment]
Could be but I even tried it without the controller. The log file doesn't show anything that would relate to the mouse cursor not showing.
