### ISSUE TITLE
Standalone version of the health hud guy?

### ISSUE THREAD

**Issue by AtlaszFox** [Wet-Boys/LethalEmotesAPI#184]
It genuinely looks awesome and I'd love to have it in a modpack I'm making, but without having the emote wheel and everything else.

**Comment by ToastedOven** [comment]
Not really gonna happen since all the keybinds can just be unbound if you don't want to have the wheel. But the mod is open source so as always you're free to fork it and strip out the healthbar stuff!

**Comment by AtlaszFox** [comment]
Where can I unbind them? I looked everywhere and I couldn't find any options related to it

**Comment by Rune580** [comment]
![image](https://github.com/user-attachments/assets/6cdd7701-31aa-4f51-b51f-67e681bb029f) or 
![image](https://github.com/user-attachments/assets/0b37aee4-e4f3-4b8a-9396-ba251733ec8c)

then 

![image](https://github.com/user-attachments/assets/13574219-6482-46d3-a637-4bb3b5a54a0d)

and then

![image](https://github.com/user-attachments/assets/feabe4aa-a30e-4390-9011-fede09f0dbd7)

finally 

![image](https://github.com/user-attachments/assets/51733ccc-775d-47bd-bdad-375fdeca93ed)

**Comment by ToastedOven** [comment]
Can you add a few more red arrows rune, I can barely see what you want me to click on

**Comment by AtlaszFox** [comment]
Ohhh I was checking LethalConfig whoops

Thanks for the arrows :^)
