### ISSUE TITLE
Unable to use terminal correctly

### ISSUE THREAD

**Issue by Kameronii** [Wet-Boys/LethalEmotesAPI#44]
Whenever i try to use the computer in the ship it doesnt lock my character in place and im able to move around the ship while the monitor types in my key inputs

**Comment by Rune580** [comment]
Do you have a modpack code you could send?

**Comment by Kameronii** [comment]
> Do you have a modpack code you could send?

I figured it out, for some reason it bugs out if i have EladsHUD enabled for some reason?

**Comment by parakatins** [comment]
> > Do you have a modpack code you could send?
> 
> I figured it out, for some reason it bugs out if i have EladsHUD enabled

if you have lethal_doors mod, the same bug happen too

**Comment by drink1101** [comment]
how do you fix it, i only left this mod and its Dependencies enabled but still have this bug. the fire start up first file is fine but the second file is bugged, you can only restart the game
