### ISSUE TITLE
Revived players dont emote correctly

### ISSUE THREAD

**Issue by ShadowRocks2** [Wet-Boys/LethalEmotesAPI#62]
when using lategame upgrades intern to revive a player, whenever they try to emote anymore in the session they are stuck flat on the ground default posing but you can hear the emote

**Comment by ShadowRocks2** [comment]
was posted as fixed but still occurs(atleast for late game upgrades`s intern revive mechanic)

**Comment by ToastedOven** [comment]
just to get a bit more info on this one as I am not familiar with lategame upgrades.

To replicate this bug, do you just need to buy this revive item and use it on someone who died?

**Comment by ShadowRocks2** [comment]
yes, have them die and then purchase intern while the monitor is selected on them

**Comment by ToastedOven** [comment]
that was an embarrassingly simple fix but it has in face been fixed

**Comment by ToastedOven** [comment]
oh right, thunderstore is kinda dead right now, I'm just gonna reopen this until I can actually push out the fix

**Comment by ShadowRocks2** [comment]
lol

**Comment by ToastedOven** [comment]
ok it's actually been pushed now
