### ISSUE TITLE
Are there keybinding options?

### ISSUE THREAD

**Issue by James-Molzer** [Wet-Boys/LethalEmotesAPI#68]
Wanted to ask if there was a way to add or change keybinding for the api mod or the BadAssComapany mod? In my case we started using the BadAssCompany mod but it has a keybinding on F for random emotes but we also use that for flashlights and nightvision toggling seeing how most games have F as a light toggle

**Comment by Rune580** [comment]
![image](https://github.com/Wet-Boys/LethalEmotesAPI/assets/12521934/3228f613-7345-416c-af5b-c60f9465f14a)

**Comment by Rune580** [comment]
all keybinds exist in the keybinds menu
