### ISSUE TITLE
Error occurred when opening the game using the mod with LethalConfig

### ISSUE THREAD

**Issue by ustaalon** [Wet-Boys/LethalEmotesAPI#70]
[Info   :   BepInEx] Loading [Custom Emotes API 1.1.8]
[Error  : Unity Log] MissingMethodException: Method not found: void LethalConfig.ConfigItems.Options.FloatSliderOptions.set_Min(single)
Stack trace:
EmotesAPI.Settings.RunAll () (at <45c46f6215af4fed84ced0846465b5b0>:0)
EmotesAPI.CustomEmotesAPI.Awake () (at <45c46f6215af4fed84ced0846465b5b0>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

I also open an issue in [LethalConfig](https://github.com/AinaVT/LethalConfig/issues/19)

**Comment by Rune580** [comment]
LethalConfig just pushed out 1.3.2 try that and see if the issue still occurs

**Comment by ustaalon** [comment]
Seems valid now. Thanks!
