### ISSUE TITLE
Force first person or stop the emote when you have a Snare Flea on your head or take damage?

### ISSUE THREAD

**Issue by NeuTraLZero** [Wet-Boys/LethalEmotesAPI#78]
Would that be a possible option? It's especially cheesy when you can see clearly in third person while a snare flea is on your head so you still know exactly where to go

**Comment by Rune580** [comment]
That was an oversight on our part, we haven't actually played the game in weeks, so we forgor about the Snare Flea.

**Comment by ToastedOven** [comment]
oh, I know what broke this, oooooooooooooooops

I'll get on it

**Comment by ToastedOven** [comment]
> That was an oversight on our part, we haven't actually played the game in weeks, so we forgor about the Snare Flea.

months* lmao
