### ISSUE TITLE
MoreCompany Cosmetics

### ISSUE THREAD

**Issue by ShadowRocks2** [Wet-Boys/LethalEmotesAPI#79]
MoreCompany cosmetics are weird about showing up, (im host btw) after an update my friends (except one) could see theirs, only difference we had was config so i deleted mine, now it does show up but only after i emote, stop, then emote again

**Comment by Rune580** [comment]
Could you send a ModPack code so that we can look into this. A log file would also be appreciated

**Comment by ShadowRocks2** [comment]
018cf995-8f9b-d46a-749d-09c7249e6662
[LogOutput.log](https://github.com/Wet-Boys/LethalEmotesAPI/files/13906541/LogOutput.log)

**Comment by Rune580** [comment]
Looking at the log it seems like this may be an issue with ModelReplacements and MoreCompany. Will have to look into it more to narrow it down though.

**Comment by ToastedOven** [comment]
I call their functions so I might just be doing it wrong

**Comment by ShadowRocks2** [comment]
> I call their functions so I might just be doing it wrong

honestly im just glad its working at all and ik must be hard making sure compatibility stays
