### ISSUE TITLE
LethalVRM Incompatibility

### ISSUE THREAD

**Issue by skorzyn** [Wet-Boys/LethalEmotesAPI#83]
**Description**
Emotes do not show or animate on the player model when using LethalVRM (by Ooseykins). Instead, the idle animation/pose continues to play.

**To Reproduce**
1. Run LethalVRM + LethalEmotesAPI/BadAssCompany from R2ModMan
2. Load into the game, preferably with someone else to test
3. Hit F for a random emote or choose one from the wheel
4. Emote plays sound and has effects but doesn't animate

**Expected behavior**
I expected the player's VRM model from LethalVRM to animate in the same way that the vanilla player would when choosing an emote.

**Logs**
[LogOutput.log](https://github.com/Wet-Boys/LethalEmotesAPI/files/13925242/LogOutput.log)

**ModPack Code**
018d0040-3023-54d1-df04-8093aaf662df

**Mods Used**
- BepInExPack (BepInEx)
- LethalVRM (Ooseykins)
- LethalConfig (AinaVT)
- LethalCompany_InputUtils (Rune580)
- LethalEmotesAPI (Gemumoddo)
- BadAssCompany (Gemumoddo)

**Additional Information**
Despite this, using emotes from MoreEmotes (Sligili) and/or BetterEmotes (KlutzyBubbles) seems to work just fine.

**Comment by ToastedOven** [comment]
fix is on my branch, gonna be in a push sometime tonight (3-4 hours)

**Comment by ToastedOven** [comment]
fixed in version 1.1.13 which is live on thunderstore
