### ISSUE TITLE
Problem with mod assembly

### ISSUE THREAD

**Issue by Paradox75831004** [Wet-Boys/LethalEmotesAPI#89]
**Freezes when restarting**
If you restart the save, you cannot interact with objects and use the emotions of mods

**For playback**
1. Launch the game
2. Die or just achieve the next save
3. Exit the menu
4. Go to the last save and get an error

**Expected behavior**
Help to find the cause of the problem

**Screenshots**
![image](https://github.com/Wet-Boys/LethalEmotesAPI/assets/72872478/2d555bd8-bde2-4977-b1e9-8bab43551a50)

**Magazines**
[LogOutput.log](https://github.com/Wet-Boys/LethalEmotesAPI/files/13931113/LogOutput.log)

**Modpack code**
The modpack code does not work (the site does not allow you to transfer it)

**Comment by ToastedOven** [comment]
Hey, can you check with version 1.2.2? It might have fixed your bug but I just kinda guessed. If you wouldn't mind a modpack code, that would greatly help as I see you have 65 mods installed
![r2modman_VV2fURuhGO](https://github.com/Wet-Boys/LethalEmotesAPI/assets/49164897/4b7e00fb-9633-4498-833c-8984ba8249a9)

**Comment by Paradox75831004** [comment]
I can't copy the code because the application didn't allow it - there were problems with the servers and so on. I'll send it a little later

**Comment by Paradox75831004** [comment]
https://drive.google.com/file/d/1ANipxUpLI_5znQXkjEZifHS8iRyniSDs/view?usp=drive_link

Here is an archive made like this

![image](https://github.com/Wet-Boys/LethalEmotesAPI/assets/72872478/00c68e83-a5e2-4e61-b179-9b02934dfcf0)

**Comment by Paradox75831004** [comment]
The problem is gone! Thanks for the quick fix - I'll continue testing
