### ISSUE TITLE
Spams console with errors due to API and BadAssCompany 

### ISSUE THREAD

**Issue by Paradox75831004** [Wet-Boys/LethalEmotesAPI#97]
**Spams console about errors**
Problem with the BadAssCompany mod to which the API is linked

**For playback**
1. Install the modpack - 018d1665-0987-6163-bba9-3a5049b8240d
2. Launch the game
3. Check the logs
4. Disable the API and BadAssCompany
5. For some reason the problem in the logs disappeared

**Expected Behavior**
Fixing spawn in error console

**Screenshots**
![image](https://github.com/Wet-Boys/LethalEmotesAPI/assets/72872478/cc5e9718-0172-4fdd-ad1b-fd74e4c5b485)

**Magazines**
[LogOutput.log](https://github.com/Wet-Boys/LethalEmotesAPI/files/13960336/LogOutput.log)

**Modpack code**
LETHAL_LONERS - 018d1665-0987-6163-bba9-3a5049b8240d

**Comment by Paradox75831004** [comment]
On version 1.2.6 everything works fine and without problems

**Comment by ToastedOven** [comment]
I'm going to tentatively close this issue since it seems to have resolved itself, but feel free to open it if you see it spamming again.
